### ISSUE TITLE
백엔드와 프론트엔드 동시 실행

### ISSUE THREAD

**Issue by yejineee** [boostcamp-2020/IssueTracker-25#44]
### 목표
- root 디렉토리에서 백엔드와 프론트엔드를 동시에 실행시킬 수 있도록 하여 반복적인 작업을 자동화한다
### 참고
https://itnext.io/4-solutions-to-run-multiple-node-js-or-npm-commands-simultaneously-9edaa6215a93

**Comment by changheedev** [comment]
루트 디렉토리의 package.json 파일에 설정해놓은 스크립트 참조해보시면 쉽게 설정 가능하실 것 같습니다. 

`run-s` : 순차 실행
`run-p` : 병렬 실행
