### ISSUE TITLE
GET /issues/:id API 구현

### ISSUE THREAD

**Issue by changheedev** [boostcamp-2020/IssueTracker-25#68]
## 목표
이슈 하나에 대한 상세 정보를 가져오는 API 구현

## 체크 리스트
- [ ] 이슈 엔티티와 연관된 엔티티의 데이터를 함께 불러온다.
- [ ] 데이터를 요청한 유저가 작성자인지 여부를 포함한다.

**Comment by yejineee** [comment]
이미 존재하는 이슈라 close 합니다.
